### ISSUE TITLE
Provide right order of media queries

### ISSUE THREAD

**Issue by hummldesign** [floatzcss/floatz-2.0#22]
flz-20 flz-25-lte-m flz-33-lte-s flz-50-lte-xs flz-100-xxs does not work, because flz-100-xxs is defined before flz-50-lte-s which overrides the previous

This should help - to be tested:

...
@media @flz-media-gte-xs {
	.flz-mx-layout(-gte-xs);
}
@media @flz-media-xs {
	.flz-mx-layout(-xs);
}
@media @flz-media-lte-xs {
	.flz-mx-layout(-lte-xs);
}
@media @flz-media-gte-xxs {
	.flz-mx-layout(-gte-xxs);
}
@media @flz-media-xxs {
	.flz-mx-layout(-xxs);
}

**Comment by hhumml** [comment]
Fixed.
